@baseUrl = http://localhost:8080/todo-list/v1

### Create new todo list item
POST {{baseUrl}}/items
Content-Type: application/json

{
  "description": "testDescription",
  "due_datetime": "2039-09-09T09:09:09Z"
}

> {%
    if (response.status === 201) {
        client.global.set("todoId", response.body.id);
    }
%}

### Create new item with invalid due datetime
POST {{baseUrl}}/items
Content-Type: application/json

{
  "description": "testDescription",
  "due_datetime": "2019-09-09T09:09:09Z"
}

### Create new item with blank description
POST {{baseUrl}}/items
Content-Type: application/json

{
  "description": "  ",
  "due_datetime": "2019-09-09T09:09:09Z"
}

### Find item by id
GET {{baseUrl}}/items/{{todoId}}
Content-Type: application/json

### Find item not found
GET {{baseUrl}}/items/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

### Update item description
PATCH {{baseUrl}}/items/{{todoId}}
Content-Type: application/json

{
  "description": "new description"
}

### Update item description not found
PATCH {{baseUrl}}/items/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "description": "new description"
}
